const who = [
  "Your sister",
  "Definitely your Mom",
  "Matt Damon",
  "No one",
  "100% for sure, You",
  "Your mum",
  "Someone far far away",
  "Your worst nightmare!",
  "That cow next door",
  "That lump of foul deformity",
  "Homer Simpson, d'oh!",
  "Frankenstein, naturally",
  "ever heard of Julius Caesar",
  "Adam, cause its his birthday",
  "Jacinda",
  "the answer to this is always, Beyonce",
  "Don. Of course",
  "He who must not be named",
  "Olaf",
  "Ronald Weasly"
]

const what = [
  "forty two",
  "Not sure, sorry",
  "Cloudy, with a chance of Rain",
  "Cats and dogs",
  "French fries",
  "Bananas, everyone loves bananas.",
  "Sugar and spice and everything nice ",
  "Sorry, watching married at first sight",
  "A phlebotomist's worst nightmare",
  "Seven deadly sins, you dingbat",
  "Blood of your first born",
  "Your infected mind has no cure",
  "I bid thee away, fair maiden!",
  "Why would you even ask that?",
  "How the hell did you come up with that?",
  "The center of the Earth",
  "Cedar trees",
  "Star Wars",
  "Climbing Mount Doom",
  "Get some sleep"  
]

const where = [
  "Turn around",
  "Have you checked your mum's closet?",
  "The dog box",
  "The blackhole of nothingness, naturally",
  "A tattoo parlor",
  "Rainbow's End",
  "Dev Academy",
  "Follow the yellow brick road",
  "At the end of the rainbow",
  "Dons house",
  "At ninny's tomb",
  "Somewhere over the rainbow",
  "Way up high",
  "Never Never Land",
  "Right up my alley",
  "I really don't care",
  "Seriously? Wherever",
  "Your house is good",
  "On a boat",
  "Do you really need to ask?",
]

const why = [
  "Because it's great",
  "Why not?",
  "It's just that way it is",
  "Because it helps",
  "...don't get me started",
  "The tartness of his face sours ripe grapes",
  "It just happens",
  "They always do",
  "Must be fate",
  "You should be shot for asking that",
  "Because thats life",
  "There is no answer to this",
  "Because Beyonce, thats why",
  "You shall never know",
  "This response is to deep for you",
  "Because you're worth it",
  "Ask your mum",
  "I blame the dog",
  "Don't worry your little mind",
  "Whale, whale, whale"
]

const how = [
  "Poorly, obviously",
  "Go with the flow",
  "I dunno, Ask Don",
  "No clue, mate",
  "You're on your own",
  "Rinse and Repeat",
  "Use Boiling Water",
  "Aloe Vera cures all",
  "If its still itchy, seek medical attention",
  "Ginger Tea is great for this",
  "With greatness",
  "Love conquers all",
  "Let me count the way",
  "By mixing it all up",
  "I'd hate to guess what's going through your mind",
  "Sometimes you just do things",
  "Figure it out yourself",
  "Have you tried Google?",
  "...I'm not a search engine",
  "Pay me and I'll tell you",
]

const will = [
  "It could happen",
  "Unfotunately no",
  "If you try hard enough",
  "Just believe and it will",
  "Absofrickinglutely!!!!!",
  "Not in this lifetime",
  "The answer is within you",
  "Yaaaaass!",
  "Nope",
  "Well... maybe",
  "Couldn't say",
  "Not in a million years",
  "When pigs fly",
  "yes, but in a galaxy far away",
  "yes but not for you",
  "Nope.",
  "Of course, Not."
]

const when = [
  "At 5pm",
  "When the moon is in the 7th house",
  "Never. Sorry... not Sorry.",
  "When you realise your inner truth",
  "In a few years, possibly",
  "Let me check with my secretary",
  "That time you said you love me",
  "When you dropped your ice cream",
  "You'll know when you grow up",
  "Tomorrow",
  "Thursday around Noon",
  "Maybe Monday? Not sure",
  "When the stars align",
  "When pigs fly",
  "On your lunchbreak",
  "Error 404",
  "What? Why do you need to know that?"
]

module.exports = {
  who,
  what,
  where,
  why,
  how,
  will,
  when
}